### ISSUE TITLE
Insufficient selections for project

### ISSUE THREAD

**Issue by Kallie-Riff** [EgMan/Patented-Project-Picker#1]
When selections are made and there are not enough to satisfy the vacancies the script perpetually runs instead of giving the user information about what went wrong. Would like an option to randomly assign to another project of same language or to update the selections myself.

**Comment by EgMan** [comment]
Hey Kalllie!

I'm having a bit of trouble understanding.  The script shouldn't care if there aren't enough people to satisfy the vacancies, it should make sure that each person is assigned not necessarily that all vacancies are filled.  Are you referring to the scenario where there are more people than there are vacancies?  I just tried this, but could not get it to hang.  

Some example data to evoke this defect would be very helpful.  

Thank you

**Comment by Kallie-Riff** [comment]
Sure I can clarify!
So the situation was there were 4 spots for a project and only two people had selected that project over all the selections. The script just ran w/o output and w/o crash.
I manually changed the selections of two trainees to get up to that vacancy of 4 and it went ahead and assigned.

**Comment by EgMan** [comment]
OooOoh I see what happened.  Thank you for the clarification.  I'll work on fixing that case here soon.

**Comment by Kallie-Riff** [comment]
You're awesome!

**Comment by EgMan** [comment]
So, looking into this more, it seems like the underlying problem is an infinite loop within the implementation of Munkres that I'm consuming.  It looks like someone else also found this bug and posted [this issue](https://github.com/bmc/munkres/issues/28).

I've committed a temporary change a76127e which avoids the usage of their DISALLOWED functionality until they can fix the issue.  

The case you described should now work.  A related change is that there is now a concept of "forced assignment," which occurs in the rare case when it is impossible to assign someone to any of their choices.  It will indicate "forced assignment" as the pick number in the console output if this occurs.

**Comment by Kallie-Riff** [comment]
So here is my output. 
![image](https://user-images.githubusercontent.com/7071773/61128324-393eef00-a477-11e9-8b9d-bf78360c4056.png)
Does it attempt to give those people the forced assignment language as their first language preference?

**Comment by EgMan** [comment]
Right now, no.  There is currently no concept of a person's "language preference" only their "project preferences."  This could be a future enhancement, and if you want this, please log it separately.  

For now, though, I'd advise you to just avoid forced assignments by telling associates they can list as many picks as they want (not just 3 or 5 or whatever you currently do).  The script accepts arbitrary amounts of picks.
Forced assignments only occur when it is absolutely impossible to fit them on all of the projects they want.  The simplest example i can think of is:
Project A has 1 spot
Project B has 1 spot
Person A _only_ wants Project A
Person B _only_ wants Project A
Since Project A only has one spot, not both of them can fit, so one of these people have to be forced onto a project which they didn't list.  The only real way around this is to ask each of them to do a full listing of projects (list them all from most desirable to least).  Or at least ask them to list as many as possible.  Not only will this allow the algorithm to place more people as their top picks, but it will make forced assignment unlikely (or impossible if they do a full listing).  

P.S. I just added a console warning for when a forced assignment occurs.
